"""Backend for the two inline popovers in the unified editor toolbar:
"Fields" (add/rename/delete note type fields) and "Card styling" (the
handful of safe CSS knobs — font, two text sizes, alignment, image cap).

Both used to be a QDialog and a proxy-click to the stock Fields dialog.
The user rejected any popup surface here — "one unified pane... not three
pop-ups and two different-looking button types" — so this module now only
ever returns JSON to JS via pycmd; every control lives in the webview
toolbar (web/editor-tools.js), and no window of ours opens from this
pane. An earlier round kept one explicit "Advanced: edit raw template"
button proxying to Anki's own stock CardLayout dialog; the user later
asked for that button gone outright too ("no one would ever use that"),
so raw template editing is reachable only through Anki's own Tools ->
Manage Note Types now, entirely outside this pane.

Card Templates (aqt.clayout.CardLayout) is a raw HTML+CSS editor built for
people who hand-write templates. The user's note types are generated by
deck-building automation and never hand-edited, so exposing the raw editor
as the primary path is the wrong default — one stray edit corrupts 115+
notes' worth of templates. The styling knobs below write only into the
note type's CSS, inside a clearly marked, idempotent override block
appended at the end. They never touch the front/back template HTML
(qfmt/afmt).

Field add/rename/delete are real schema changes (col.models.add_field /
rename_field / remove_field, same primitives the stock Fields dialog
itself uses) — they can touch every note of that type, and Anki's own
backend may surface a sync-required prompt as a result. That prompt is
Anki's, not ours, and is explicitly acceptable; nothing in this module
opens a window of its own.
"""

import re

_BLOCK_START = "/* BEGIN Anki Plus: card styling (generated by the Card styling panel — edits here are overwritten on next Save; use the panel instead) */"
_BLOCK_END = "/* END Anki Plus: card styling */"
_BLOCK_RE = re.compile(
    re.escape(_BLOCK_START) + r".*?" + re.escape(_BLOCK_END),
    re.DOTALL,
)

_DEFAULTS = {
    "font": "",
    "base_size": 20,
    "answer_size": 24,
    "align": "center",
    "image_max_height": 500,
}


def _parse_existing(css: str) -> dict:
    """Best-effort read-back of the panel's own block, so reopening the
    popover shows what's actually applied instead of resetting to
    defaults every time."""
    m = _BLOCK_RE.search(css or "")
    values = dict(_DEFAULTS)
    if not m:
        return values
    block = m.group(0)
    fm = re.search(r'font-family:\s*"([^"]*)"', block)
    if fm:
        values["font"] = fm.group(1)
    bm = re.search(r"\.card\s*\{[^}]*font-size:\s*([\d.]+)px", block)
    if bm:
        values["base_size"] = int(float(bm.group(1)))
    am = re.search(r"#answer\s*~\s*\*\s*\{[^}]*font-size:\s*([\d.]+)px", block)
    if am:
        values["answer_size"] = int(float(am.group(1)))
    al = re.search(r"text-align:\s*(left|center|right)", block)
    if al:
        values["align"] = al.group(1)
    im = re.search(r"\.card img\s*\{[^}]*max-height:\s*([\d.]+)px", block)
    if im:
        values["image_max_height"] = int(float(im.group(1)))
    return values


def _build_block(font: str, base_size: int, answer_size: int, align: str, image_max_height: int) -> str:
    font_rule = ""
    if font.strip():
        escaped = font.strip().replace('"', '\\"')
        font_rule = f'font-family: "{escaped}", sans-serif;\n'
    return (
        f"{_BLOCK_START}\n"
        f".card {{\n{font_rule}font-size: {base_size}px;\ntext-align: {align};\n}}\n"
        f".card img {{\nmax-height: {image_max_height}px;\n}}\n"
        # Stock Anki's default "Basic" family of note types (and every note
        # type this addon has seen generated from them) puts `<hr id=answer>`
        # between {{FrontSide}} and the answer content in the back template —
        # a long-standing Anki convention, not something we write ourselves.
        # `#answer ~ *` reaches only the siblings that render after that
        # marker, i.e. the answer-side content, without touching qfmt/afmt.
        # A note type that doesn't use the convention just won't have this
        # rule take effect — harmless, not corrupting.
        f"#answer ~ * {{\nfont-size: {answer_size}px;\n}}\n"
        f"{_BLOCK_END}"
    )


def apply_styling(css: str, font: str, base_size: int, answer_size: int, align: str, image_max_height: int) -> str:
    """Pure function (no Qt/collection access) so it's easy to unit test."""
    block = _build_block(font, base_size, answer_size, align, image_max_height)
    if _BLOCK_RE.search(css or ""):
        return _BLOCK_RE.sub(block, css)
    sep = "\n\n" if css and not css.endswith("\n\n") else ""
    return (css or "") + sep + block + "\n"


def remove_styling(css: str) -> str:
    """Strip the override block entirely — the Reset path."""
    stripped = _BLOCK_RE.sub("", css or "")
    return re.sub(r"\n{3,}", "\n\n", stripped).strip() + "\n" if stripped.strip() else stripped


def _current_notetype(editor):
    """editor.note is the loaded Note (a plain attribute on the legacy
    Editor — aqt.editor re-exports aqt.editor_legacy's Editor, which has
    no get_note_info; that's a NewEditor-only method and calling it here
    is what threw AttributeError in production). note.note_type() is the
    live NotetypeDict, the same thing Editor.note_type()/onFields uses."""
    if editor.note is None:
        return None
    return editor.note.note_type()


def _field_list(notetype: dict) -> list:
    return [{"ord": f["ord"], "name": f["name"]} for f in notetype["flds"]]


def get_fields(editor) -> dict:
    nt = _current_notetype(editor)
    if nt is None:
        return {"error": "No note is loaded."}
    return {"fields": _field_list(nt), "notetypeName": nt["name"]}


def mutate_fields(editor, op: str, payload: dict) -> dict:
    """add / rename / delete, via the same col.models primitives the stock
    Fields dialog uses (add_field/rename_field/remove_field then
    update_dict — "Modifies schema" per their own docstrings, exactly the
    schema-mod path the user asked this route through)."""
    mw = editor.mw
    nt = _current_notetype(editor)
    if nt is None:
        return {"error": "No note is loaded."}
    try:
        if op == "add":
            name = (payload.get("name") or "").strip()
            if not name:
                return {"error": "Field name can't be empty."}
            if any(f["name"] == name for f in nt["flds"]):
                return {"error": "A field with that name already exists."}
            field = mw.col.models.new_field(name)
            mw.col.models.add_field(nt, field)
        elif op == "rename":
            ord_ = payload.get("ord")
            new_name = (payload.get("newName") or "").strip()
            if not new_name:
                return {"error": "Field name can't be empty."}
            field = next((f for f in nt["flds"] if f["ord"] == ord_), None)
            if field is None:
                return {"error": "Field not found."}
            if any(f["name"] == new_name for f in nt["flds"] if f is not field):
                return {"error": "A field with that name already exists."}
            mw.col.models.rename_field(nt, field, new_name)
        elif op == "delete":
            ord_ = payload.get("ord")
            field = next((f for f in nt["flds"] if f["ord"] == ord_), None)
            if field is None:
                return {"error": "Field not found."}
            if len(nt["flds"]) <= 1:
                return {"error": "A note type needs at least one field."}
            mw.col.models.remove_field(nt, field)
        else:
            return {"error": "Unknown operation."}
        mw.col.models.update_dict(nt)
    except Exception as exc:
        return {"error": str(exc) or "Could not update fields."}
    # Schema change: field set on screen must reflect the new notetype.
    # mw.reset() is the blunt, always-correct way every surface (editor,
    # browser list, deck browser counts) picks that up — the same
    # heavy-handed refresh a stock schema-changing op in Anki triggers.
    mw.reset()
    nt2 = mw.col.models.get(nt["id"])
    return {"fields": _field_list(nt2), "notetypeName": nt2["name"]}


def get_styling(editor) -> dict:
    nt = _current_notetype(editor)
    if nt is None:
        return {"error": "No note is loaded."}
    return _parse_existing(nt.get("css", ""))


def apply_styling_cmd(editor, payload: dict) -> dict:
    mw = editor.mw
    nt = _current_notetype(editor)
    if nt is None:
        return {"error": "No note is loaded."}
    try:
        base_size = int(payload.get("base_size", _DEFAULTS["base_size"]))
        answer_size = int(payload.get("answer_size", _DEFAULTS["answer_size"]))
        image_max_height = int(payload.get("image_max_height", _DEFAULTS["image_max_height"]))
        align = payload.get("align") or _DEFAULTS["align"]
        if align not in ("left", "center", "right"):
            align = _DEFAULTS["align"]
        font = payload.get("font") or ""
        nt["css"] = apply_styling(nt.get("css", ""), font, base_size, answer_size, align, image_max_height)
        mw.col.models.update_dict(nt)
    except Exception as exc:
        return {"error": str(exc) or "Could not apply styling."}
    mw.reset()
    return {"ok": True}


def reset_styling_cmd(editor) -> dict:
    mw = editor.mw
    nt = _current_notetype(editor)
    if nt is None:
        return {"error": "No note is loaded."}
    try:
        nt["css"] = remove_styling(nt.get("css", ""))
        mw.col.models.update_dict(nt)
    except Exception as exc:
        return {"error": str(exc) or "Could not reset styling."}
    mw.reset()
    return {"ok": True}


def on_message(handled, message, context):
    """ba:fields:* and ba:styling:* pycmd dispatch — see __init__.py's
    _on_js_message. Every handler here returns JSON directly to the JS
    callback; none of them ever construct a Qt window."""
    import json

    from aqt.editor import Editor

    if handled[0] or not isinstance(message, str):
        return handled
    if not (message.startswith("ba:fields:") or message.startswith("ba:styling:")):
        return handled
    if not isinstance(context, Editor):
        return (True, {"error": "The editor is no longer open."})

    try:
        if message == "ba:fields:get":
            return (True, get_fields(context))
        if message.startswith("ba:fields:mutate:"):
            payload = json.loads(message[len("ba:fields:mutate:"):])
            op = payload.get("op", "")
            return (True, mutate_fields(context, op, payload))
        if message == "ba:styling:get":
            return (True, get_styling(context))
        if message.startswith("ba:styling:apply:"):
            payload = json.loads(message[len("ba:styling:apply:"):])
            return (True, apply_styling_cmd(context, payload))
        if message == "ba:styling:reset":
            return (True, reset_styling_cmd(context))
    except Exception as exc:
        return (True, {"error": str(exc) or "Something went wrong."})
    return handled
