"""A simple, safe styling panel for the "Card styling..." menu item.

Card Templates (aqt.clayout.CardLayout) is a raw HTML+CSS editor built for
people who hand-write templates. The user's note types are generated by
deck-building automation and never hand-edited, so exposing the raw editor
as the primary path is the wrong default — one stray edit corrupts 115
notes' worth of templates. This dialog exposes the handful of knobs that
actually matter (font, two text sizes, alignment, image cap) and writes
them into the note type's *styling* (CSS) only, inside a clearly marked,
idempotent override block appended at the end. It never touches the
front/back template HTML (qfmt/afmt) — Save only ever calls
NotetypeDict["css"] = <front templates untouched> + override block.

The raw editor stays one click away behind "Advanced: edit raw template"
in the same menu (see web/editor-tools.js's #ba-editor-menu) — this panel
replaces it as the *default*, not as the only path.
"""

import re
from typing import Optional

from aqt.qt import (
    QComboBox,
    QCompleter,
    QDialog,
    QDialogButtonBox,
    QFontDatabase,
    QFormLayout,
    QLabel,
    QPushButton,
    QSpinBox,
    Qt,
    QVBoxLayout,
)

# Everything between these markers is owned by this dialog. Save rewrites
# the whole block in place (regex find/replace); Reset deletes it outright,
# restoring the note type's original, hand-authored-or-generated CSS with
# zero trace left behind — that's what makes this reversible.
_BLOCK_START = "/* BEGIN Anki Plus: card styling (generated by the Card styling panel — edits here are overwritten on next Save; use the panel instead) */"
_BLOCK_END = "/* END Anki Plus: card styling */"
_BLOCK_RE = re.compile(
    re.escape(_BLOCK_START) + r".*?" + re.escape(_BLOCK_END),
    re.DOTALL,
)

_DEFAULTS = {
    "font": "",
    "base_size": 20,
    "answer_size": 24,
    "align": "center",
    "image_max_height": 500,
}

_ALIGN_CHOICES = [("Left", "left"), ("Center", "center"), ("Right", "right")]


def _parse_existing(css: str) -> dict:
    """Best-effort read-back of the panel's own block, so reopening the
    dialog shows what's actually applied instead of resetting to defaults
    every time."""
    m = _BLOCK_RE.search(css or "")
    values = dict(_DEFAULTS)
    if not m:
        return values
    block = m.group(0)
    fm = re.search(r'font-family:\s*"([^"]*)"', block)
    if fm:
        values["font"] = fm.group(1)
    bm = re.search(r"\.card\s*\{[^}]*font-size:\s*([\d.]+)px", block)
    if bm:
        values["base_size"] = int(float(bm.group(1)))
    am = re.search(r"#answer\s*~\s*\*\s*\{[^}]*font-size:\s*([\d.]+)px", block)
    if am:
        values["answer_size"] = int(float(am.group(1)))
    al = re.search(r"text-align:\s*(left|center|right)", block)
    if al:
        values["align"] = al.group(1)
    im = re.search(r"\.card img\s*\{[^}]*max-height:\s*([\d.]+)px", block)
    if im:
        values["image_max_height"] = int(float(im.group(1)))
    return values


def _build_block(font: str, base_size: int, answer_size: int, align: str, image_max_height: int) -> str:
    font_rule = ""
    if font.strip():
        escaped = font.strip().replace('"', '\\"')
        font_rule = f'font-family: "{escaped}", sans-serif;\n'
    return (
        f"{_BLOCK_START}\n"
        f".card {{\n{font_rule}font-size: {base_size}px;\ntext-align: {align};\n}}\n"
        f".card img {{\nmax-height: {image_max_height}px;\n}}\n"
        # Stock Anki's default "Basic" family of note types (and every note
        # type this addon has seen generated from them) puts `<hr id=answer>`
        # between {{FrontSide}} and the answer content in the back template —
        # a long-standing Anki convention, not something we write ourselves.
        # `#answer ~ *` reaches only the siblings that render after that
        # marker, i.e. the answer-side content, without touching qfmt/afmt.
        # A note type that doesn't use the convention just won't have this
        # rule take effect — harmless, not corrupting.
        f"#answer ~ * {{\nfont-size: {answer_size}px;\n}}\n"
        f"{_BLOCK_END}"
    )


def apply_styling(css: str, font: str, base_size: int, answer_size: int, align: str, image_max_height: int) -> str:
    """Pure function (no Qt/collection access) so it's easy to unit test."""
    block = _build_block(font, base_size, answer_size, align, image_max_height)
    if _BLOCK_RE.search(css or ""):
        return _BLOCK_RE.sub(block, css)
    sep = "\n\n" if css and not css.endswith("\n\n") else ""
    return (css or "") + sep + block + "\n"


def remove_styling(css: str) -> str:
    """Strip the override block entirely — the Reset path."""
    stripped = _BLOCK_RE.sub("", css or "")
    return re.sub(r"\n{3,}", "\n\n", stripped).strip() + "\n" if stripped.strip() else stripped


class CardStylingDialog(QDialog):
    def __init__(self, mw, notetype, parent=None):
        super().__init__(parent)
        self.mw = mw
        self.notetype = notetype
        self.setWindowTitle("Card styling — " + notetype.get("name", ""))
        self.setMinimumWidth(360)

        values = _parse_existing(notetype.get("css", ""))

        layout = QVBoxLayout(self)
        form = QFormLayout()
        layout.addLayout(form)

        self.font_combo = QComboBox()
        self.font_combo.setEditable(True)
        self.font_combo.setInsertPolicy(QComboBox.InsertPolicy.NoInsert)
        families = [""] + sorted(QFontDatabase.families())
        self.font_combo.addItems(families)
        self.font_combo.setEditText(values["font"])
        completer = QCompleter(families, self.font_combo)
        completer.setCaseSensitivity(Qt.CaseSensitivity.CaseInsensitive)
        completer.setCompletionMode(QCompleter.CompletionMode.PopupCompletion)
        self.font_combo.setCompleter(completer)
        form.addRow("Font (blank = card's own default):", self.font_combo)

        self.base_size = QSpinBox()
        self.base_size.setRange(6, 300)
        self.base_size.setSuffix(" px")
        self.base_size.setValue(values["base_size"])
        form.addRow("Base text size:", self.base_size)

        self.answer_size = QSpinBox()
        self.answer_size.setRange(6, 300)
        self.answer_size.setSuffix(" px")
        self.answer_size.setValue(values["answer_size"])
        form.addRow("Answer text size:", self.answer_size)

        self.align_combo = QComboBox()
        for label, _value in _ALIGN_CHOICES:
            self.align_combo.addItem(label)
        current_align_index = [v for _l, v in _ALIGN_CHOICES].index(values["align"]) if values["align"] in [v for _l, v in _ALIGN_CHOICES] else 1
        self.align_combo.setCurrentIndex(current_align_index)
        form.addRow("Text alignment:", self.align_combo)

        self.image_height = QSpinBox()
        self.image_height.setRange(20, 4000)
        self.image_height.setSuffix(" px")
        self.image_height.setValue(values["image_max_height"])
        form.addRow("Image max height:", self.image_height)

        note = QLabel(
            "Only styling (CSS) changes. Front/Back template HTML is never touched."
        )
        note.setWordWrap(True)
        note.setStyleSheet("color: palette(mid); font-size: 11px;")
        layout.addWidget(note)

        buttons = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Save | QDialogButtonBox.StandardButton.Cancel
        )
        self.reset_button = QPushButton("Reset to card's own styling")
        buttons.addButton(self.reset_button, QDialogButtonBox.ButtonRole.DestructiveRole)
        buttons.accepted.connect(self.save)
        buttons.rejected.connect(self.reject)
        self.reset_button.clicked.connect(self.reset)
        layout.addWidget(buttons)

    def _write(self, new_css: str) -> None:
        from aqt.operations import CollectionOp

        notetype = self.notetype
        notetype["css"] = new_css

        def op(col):
            return col.models.update_dict(notetype)

        CollectionOp(parent=self, op=op).run_in_background()

    def save(self) -> None:
        new_css = apply_styling(
            self.notetype.get("css", ""),
            self.font_combo.currentText(),
            self.base_size.value(),
            self.answer_size.value(),
            _ALIGN_CHOICES[self.align_combo.currentIndex()][1],
            self.image_height.value(),
        )
        self._write(new_css)
        self.accept()

    def reset(self) -> None:
        new_css = remove_styling(self.notetype.get("css", ""))
        self._write(new_css)
        self.accept()


def open_card_styling(editor) -> None:
    """Entry point from the JS bridge (see __init__.py's ba:card-styling:open
    handler). Mirrors Editor.onFields/onCardLayout's own get_note_info()
    round-trip so we see the same in-progress field edits those stock
    dialogs do."""
    mw = editor.mw

    def on_note_info(note_info) -> None:
        notetype = mw.col.models.get(note_info.mid)
        if notetype is None:
            return
        dialog = CardStylingDialog(mw, notetype, parent=editor.parentWindow)
        dialog.exec()

    editor.get_note_info(on_note_info)
